import "./globals.css";
import type { Metadata } from "next";
import { Viewport } from "next/dist/lib/metadata/types/extra-types";
import { Manrope } from "next/font/google";
import Head from "next/head";

const inter = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 0.5,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
